#!/usr/bin/env node
// Reads Foundry compilation artifacts from packages/contracts/out and emits
// packages/shared/src/abi.ts with each ABI exported as a `readonly` tuple
// const so viem/wagmi can infer call argument and return types.
//
// Run via:
//   pnpm export-abis
//
// Pre-req: `pnpm --filter @prism/contracts build` (or `forge build`) so that
// the artifact JSON files exist under packages/contracts/out.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface Mapping {
  /** Exported `const` name in `packages/shared/src/abi.ts`. */
  exportName: string;
  /** Path under packages/contracts/out, e.g. "IVault.sol/IVault.json". */
  artifact: string;
}

// Each entry maps an `<ExportName>Abi` const to the Foundry artifact whose
// `abi` field should be inlined. Interfaces are intentionally used as the
// source-of-truth surface where the implementing contract is not yet built.
const MAPPINGS: Mapping[] = [
  { exportName: "Vault", artifact: "IVault.sol/IVault.json" },
  { exportName: "VaultFactory", artifact: "IVaultFactory.sol/IVaultFactory.json" },
  { exportName: "ProtocolHook", artifact: "IProtocolHook.sol/IProtocolHook.json" },
  { exportName: "BellStrategy", artifact: "IStrategy.sol/IStrategy.json" },
  { exportName: "ChainlinkAdapter", artifact: "IChainlinkAdapter.sol/IChainlinkAdapter.json" },
];

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const ARTIFACT_DIR = join(REPO_ROOT, "packages", "contracts", "out");
const OUTPUT_FILE = join(REPO_ROOT, "packages", "shared", "src", "abi.ts");

interface Artifact {
  abi?: unknown[];
}

function loadAbi(mapping: Mapping): { abi: unknown[]; found: boolean } {
  const path = join(ARTIFACT_DIR, mapping.artifact);
  if (!existsSync(path)) {
    return { abi: [], found: false };
  }
  const raw = readFileSync(path, "utf8");
  const parsed = JSON.parse(raw) as Artifact;
  if (!Array.isArray(parsed.abi)) {
    throw new Error(`artifact ${mapping.artifact} has no abi array`);
  }
  return { abi: parsed.abi, found: true };
}

function formatAbiLiteral(abi: unknown[]): string {
  // JSON.stringify is deterministic enough for this tool — Foundry already
  // emits stable ordering. Two-space indent matches the surrounding TS.
  return JSON.stringify(abi, null, 2);
}

function render(entries: { exportName: string; abi: unknown[]; found: boolean }[]): string {
  const banner = `// AUTO-GENERATED by scripts/export-abis.ts — do not edit by hand.
// Regenerate with: pnpm export-abis
//
// Source: packages/contracts/out/<ContractName>.sol/<ContractName>.json
// (run \`pnpm --filter @prism/contracts build\` first).
`;

  const blocks = entries.map(({ exportName, abi, found }) => {
    const constName = `${exportName}Abi`;
    const note = found ? "" : `// NOTE: artifact missing at generation time — placeholder empty ABI.\n`;
    return `${note}export const ${constName} = ${formatAbiLiteral(abi)} as const;\nexport type ${constName} = typeof ${constName};\n`;
  });

  return `${banner}\n${blocks.join("\n")}`;
}

function main(): void {
  const entries = MAPPINGS.map((m) => ({
    exportName: m.exportName,
    ...loadAbi(m),
  }));

  const missing = entries.filter((e) => !e.found);
  for (const m of missing) {
    process.stderr.write(`warn: artifact missing for ${m.exportName} — emitting empty ABI\n`);
  }

  const output = render(entries);
  writeFileSync(OUTPUT_FILE, output);

  const summary = entries
    .map((e) => `  ${e.exportName.padEnd(20)} ${e.found ? `${e.abi.length} entries` : "missing"}`)
    .join("\n");
  process.stdout.write(`wrote ${OUTPUT_FILE}\n${summary}\n`);
}

main();
